package fifo_tests_pkg;
	import uvm_pkg::*;
	import tb_params_pkg::DATA_WIDTH;
	import fifo_rd_agent_config_pkg::*;
	import fifo_wr_agent_config_pkg::*;
	import fifo_rd_agent_pkg::*;
	import fifo_wr_agent_pkg::*;
	import fifo_sequence_pkg::*;
	import fifo_env_config_pkg::*;
	import fifo_env_pkg::*;
	`include "uvm_macros.svh"
	`include "fifo_base_test.sv"
	`include "fifo_write_test.sv"
	`include "fifo_write_read_test.sv";
endpackage: fifo_tests_pkg
