package fifo_rd_agent_pkg;
	import uvm_pkg::*;
	import tb_params_pkg::DATA_WIDTH;
	`include "uvm_macros.svh"
	`include "fifo_rd_transaction_item.sv"
	`include "fifo_rd_monitor.sv"
	`include "fifo_rd_driver.sv"
	`include "fifo_rd_sequencer.sv"
	import fifo_rd_agent_config_pkg::*;
	`include "fifo_rd_agent.sv"
endpackage: fifo_rd_agent_pkg
